#!/bin/bash

if [ -d "rtags" ]; then
    cd rtags
    git pull
else
    git clone --recursive https://github.com/Andersbakken/rtags.git
    cd rtags
fi

cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=1 .
make
