#!/bin/bash

# neotree (https://github.com/jaypei/emacs-neotree)
if [ ! -d "emacs-neotree" ]; then
    echo ">> Cloning 'emacs-neotree'"
    git clone https://github.com/jaypei/emacs-neotree.git
fi

# popup-el (https://github.com/auto-complete/popup-el)
if [ ! -d "popup-el" ]; then
    echo ">> Cloning 'popup-el'"
    git clone https://github.com/auto-complete/popup-el.git
fi

# auto-complete (https://github.com/auto-complete/auto-complete)
if [ ! -d "auto-complete" ]; then
    echo ">> Cloning 'auto-complete'"
    git clone https://github.com/auto-complete/auto-complete.git
fi

# emacs-ac-etags (https://github.com/syohex/emacs-ac-etags)
if [ ! -d "emacs-ac-etags" ]; then
    echo ">> Cloning 'emacs-ac-etags'"
    git clone https://github.com/syohex/emacs-ac-etags.git
fi

# magit (https://github.com/magit/magit.git)
if [ ! -d "magit" ]; then
    echo ">> Cloning 'magit'"
    git clone https://github.com/magit/magit.git
    git clone https://github.com/magit/ghub.git
    cd magit
    make
fi
